repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
<<<<<<< HEAD
    rev: v2.3.0
=======
    rev: v4.3.0
>>>>>>> cfd495d (first commit)
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
<<<<<<< HEAD
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
=======
>>>>>>> cfd495d (first commit)
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
<<<<<<< HEAD
        ]
=======
        ]
    - id: black
      name: black
      entry: black
      language: system
      types: [ python ]
>>>>>>> cfd495d (first commit)
